// AUTO-GENERATED by scripts/generate-hsk-data.mts — DO NOT EDIT
// Fast lookup maps for HSK 3.0 (2021) — all levels

import { hsk1 } from './hsk-1'
import { hsk2 } from './hsk-2'
import { hsk3 } from './hsk-3'
import { hsk4 } from './hsk-4'
import { hsk5 } from './hsk-5'
import { hsk6 } from './hsk-6'
import { hsk79 } from './hsk-7-9'
import type { HskByHanzi, HskByLevel, HskLevel, HskWord } from './types'

export type { HskByHanzi, HskByLevel, HskLevel, HskWord }

/** All HSK words across all levels */
export const allHskWords: HskWord[] = [
  ...hsk1,
  ...hsk2,
  ...hsk3,
  ...hsk4,
  ...hsk5,
  ...hsk6,
  ...hsk79,
]

/**
 * Lookup by simplified hanzi → HskWord[]
 * O(1) — perfect for flashcard display & search
 */
export const hskByHanzi: HskByHanzi = new Map()
for (const word of allHskWords) {
  const existing = hskByHanzi.get(word.simplified) ?? []
  existing.push(word)
  hskByHanzi.set(word.simplified, existing)
}

/**
 * Lookup by HSK level → HskWord[]
 * O(1) — perfect for deck generation
 */
export const hskByLevel: HskByLevel = new Map()
for (const word of allHskWords) {
  const existing = hskByLevel.get(word.level) ?? []
  existing.push(word)
  hskByLevel.set(word.level, existing)
}

/** Get words for a specific level, sorted by frequency (most common first) */
export function getWordsByLevel(level: HskLevel): HskWord[] {
  return hskByLevel.get(level) ?? []
}

/** Find a word by simplified hanzi (returns first match if duplicates) */
export function findWord(simplified: string): HskWord | undefined {
  return hskByHanzi.get(simplified)?.[0]
}

/** Get total word count per level */
export function getWordCount(level: HskLevel): number {
  return hskByLevel.get(level)?.length ?? 0
}

// Re-export individual level arrays
export { hsk1, hsk2, hsk3, hsk4, hsk5, hsk6, hsk79 }
