/**
 * HSK 3.0 (2021) Vocabulary Types
 * Static data — NO DB query needed
 */

export type HskLevel = 1 | 2 | 3 | 4 | 5 | 6 | 7 // 7 = HSK 7-9

/**
 * Part-of-Speech tags (Chinese grammar categories)
 * Used for weak-point analysis and card categorisation
 */
export type PosTag =
  | '动词' // กริยา (verb)
  | '名词' // คำนาม (noun)
  | '形容词' // คุณศัพท์ (adjective)
  | '副词' // กริยาวิเศษณ์ (adverb)
  | '连词' // คำเชื่อม (conjunction)
  | '量词' // ลักษณนาม (measure word)
  | '介词' // บุพบท (preposition)
  | '代词' // สรรพนาม (pronoun)
  | '其他' // อื่นๆ (other)

/**
 * Example sentence for a vocabulary word.
 * Target word is wrapped in [[double brackets]] in every field.
 *
 * Example:
 *   zh:     "我很[[爱]]我的家人。"
 *   pinyin: "Wǒ hěn [[ài]] wǒ de jiārén。"
 *   th:     "ฉัน[[รัก]]ครอบครัวของฉันมาก"
 */
export interface HskSentence {
  zh: string
  pinyin: string
  th: string
}

export interface HskWord {
  /** Simplified Chinese (e.g. 爱) */
  simplified: string
  /** Traditional Chinese (e.g. 愛) */
  traditional: string
  /** Pinyin with tone marks (e.g. ài) */
  pinyin: string
  /** English definition(s) */
  definitionEn: string
  /** HSK level 1-6, or 7 for HSK 7-9 */
  level: HskLevel
  /**
   * Frequency rank within this HSK level (1 = most frequent).
   * Based on row order from HSK 3.0 official word list.
   */
  frequencyRank: number
  /**
   * Thai meaning — generated by Qwen3 AI, baked into static bundle.
   * Undefined until generate-thai-meanings script has been run.
   */
  meaningTh?: string
  /**
   * Part-of-speech tag — generated by DeepSeek, baked into static bundle.
   * Used for weak-point analysis per grammar category.
   */
  pos?: PosTag
  /**
   * Example sentence with target word wrapped in [[brackets]].
   * Generated by DeepSeek, baked into static bundle.
   */
  sentence?: HskSentence
}

/** Lookup by simplified hanzi → HskWord[] (multiple entries possible) */
export type HskByHanzi = Map<string, HskWord[]>

/** Lookup by level → HskWord[] */
export type HskByLevel = Map<HskLevel, HskWord[]>
